## 1# pwd (Verifica onde esta localizado a pasta)
## 2# git config --global user.name "nome_do_git_aqui_dentro"  (Coloque o nome do git certinho)
## 3# git config --global user.email "prometheusamvs1@gmail.com" (mesmo email do git)
## 4# clear (limpa o terminal)
## 5# git init (inicializa o repositorio)
## 6# ls (mostra o arquivo dentro da pasta)
## 7# ls -la (mostra quantos arquivos ha dentro da pasta)
## 8# git branch -m main (Por boas praticas devemos trocar a branch master para o main )
## 9# git push origin main --delete master (Vai deletar a master e deixar apenas a main)
## 10# git status (Mostra o status dos arquivo)
## 11# git add . (Faz isso apos fazer uma modificacao ou adicionar um arquivo novo, somente depois use commit)
## 12# git commit -m "mensagem" (Preparando o arquivo antes de enviar)
## 13# Vá no site git hub e cria um novo repositorio (É preciso fazer isso antes de qualquer outra coisa de push)
## 14# Vai em code e copia o HTTPS e coloca o comando no terminal > git remote add origin link
## 15# git branch (Vai mostrar o arquivo main)
## 16# git branch -r (Vai mostrar a branch localmente, caso apareça vermelho quer dizer que está certo)
## 17# git push -u origin main (Vai publicar no site)